# Visualization

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
%matplotlib inline

## Data loading

In [33]:
pm25_05t = pd.read_json('pm25_05t.json', dtype='object')
pm25_50t = pd.read_json('pm25_50t.json', dtype='object')
pm25_52t = pd.read_json('pm25_52t.json', dtype='object')
pm25_53t = pd.read_json('pm25_53t.json', dtype='object')
pm25_59t = pd.read_json('pm25_59t.json', dtype='object')
pm25_61t = pd.read_json('pm25_61t.json', dtype='object')
pm25_05t.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1200 entries, 0 to 1199
Data columns (total 3 columns):
05t_PM2.5 (ug/m3)    1200 non-null object
Date                 1200 non-null object
Time                 1200 non-null object
dtypes: object(3)
memory usage: 37.5+ KB

In [34]:
table_list = [pm25_05t,pm25_50t,pm25_52t,pm25_53t,pm25_59t,pm25_61t]
for table in table_list:
    table['DateTime'] = table[['Date','Time']].apply(lambda row: ' '.join(row), axis=1)
    #table['Date'].astype('datetime64[ns]')
    #table['Time'].astype('datetime64[ns]')
    #table['DateTime'].astype('datetime64[ns]')

TypeError: ("unsupported operand type(s) for +: 'Timestamp' and 'str'", 'occurred at index 0')

In [19]:
pm25_05t

     05t_PM2.5 (ug/m3)       Date      Time
0                25.78 2018-01-01  00-00-00
1                18.94 2018-01-01  01-00-00
2                16.83 2018-01-01  02-00-00
3                11.90 2018-01-01  03-00-00
4                 9.07 2018-01-01  04-00-00
5                10.97 2018-01-01  05-00-00
6                 9.97 2018-01-01  06-00-00
7                 9.14 2018-01-01  07-00-00
8                12.93 2018-01-01  08-00-00
9                10.94 2018-01-01  09-00-00
10                9.14 2018-01-01  10-00-00
11               12.94 2018-01-01  11-00-00
12               10.90 2018-01-01  12-00-00
13                8.17 2018-01-01  13-00-00
14               13.07 2018-01-01  14-00-00
15               15.00 2018-01-01  15-00-00
16               15.27 2018-01-01  16-00-00
17               22.93 2018-01-01  17-00-00
18               21.24 2018-01-01  18-00-00
19               28.00 2018-01-01  19-00-00
20               28.00 2018-01-01  20-00-00
21               27.97 2018-01-01  21-00-00
22               27.07 2018-01-01  22-00-00
23               28.97 2018-01-01  23-00-00
24               27.90 2018-01-02  00-00-00
25               25.24 2018-01-02  01-00-00
26               31.94 2018-01-02  02-00-00
27               30.19 2018-01-02  03-00-00
28               36.20 2018-01-02  04-00-00
29               42.26 2018-01-02  05-00-00
...                ...        ...       ...
1170             44.89 2018-02-18  18-00-00
1171             42.14 2018-02-18  19-00-00
1172             45.86 2018-02-18  20-00-00
1173             41.86 2018-02-18  21-00-00
1174             37.96 2018-02-18  22-00-00
1175             37.07 2018-02-18  23-00-00
1176             39.14 2018-02-19  00-00-00
1177             42.86 2018-02-19  01-00-00
1178             38.93 2018-02-19  02-00-00
1179             37.00 2018-02-19  03-00-00
1180             37.04 2018-02-19  04-00-00
1181             37.86 2018-02-19  05-00-00
1182             34.18 2018-02-19  06-00-00
1183             39.21 2018-02-19  07-00-00
1184             44.82 2018-02-19  08-00-00
1185             40.00 2018-02-19  09-00-00
1186             40.18 2018-02-19  10-00-00
1187             45.11 2018-02-19  11-00-00
1188             47.72 2018-02-19  12-00-00
1189             39.79 2018-02-19  13-00-00
1190             33.65 2018-02-19  14-00-00
1191             23.93 2018-02-19  15-00-00
1192             22.21 2018-02-19  16-00-00
1193             27.96 2018-02-19  17-00-00
1194             26.79 2018-02-19  18-00-00
1195             20.75 2018-02-19  19-00-00
1196             13.93 2018-02-19  20-00-00
1197             11.89 2018-02-19  21-00-00
1198              9.07 2018-02-19  22-00-00
1199             10.90 2018-02-19  23-00-00

[1200 rows x 3 columns]